[dependencies]
mnist = { path = "pots/mnist_1.0.0.toml" }
iris = { path = "pots/iris_1.0.0.toml" }
fashion_mnist = { path = "pots/fashion_mnist_1.0.0.toml" }
mtcars = { path = "pots/mtcars_1.0.0.toml" }
