name = "fashion_mnist"
description = """Fashion-MNIST: a Novel Image Dataset for Benchmarking Machine Learning Algorithms."""
version = "1.0.0"
homepage = "https://github.com/zalandoresearch/fashion-mnist"
licence = "MIT"

[[files]]
url = "http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/train-images-idx3-ubyte.gz"
md5 = "8d4fb7e6c68d591d4c3dfef9ec88bf0d"

[[files]]
url = "http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/train-labels-idx1-ubyte.gz"
md5 = "25c81989df183df01b3e8a0aad5dffbe"

[[files]]
url = "http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/t10k-images-idx3-ubyte.gz"
md5 = "bef4ecab320f06d8554ea6380940ec79"

[[files]]
url = "http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/t10k-labels-idx1-ubyte.gz"
md5 = "bb300cfdad3c16e7a12a480ee83cd310"
